# TCL File Generated by Component Editor 9.1sp2
# Fri Dec 10 12:01:23 JST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ps2_component "ps2_component" v1.0
# | null 2010.12.10.12:01:23
# | 
# | 
# | C:/PROJECT_DATA/yokoyama/DE0/nios2_fpu/altera_up_ps2/ps2_component.v
# | 
# |    ./Altera_UP_PS2.v syn, sim
# |    ./Altera_UP_PS2_Command_Out.v syn, sim
# |    ./Altera_UP_PS2_Data_In.v syn, sim
# |    ./ps2_component.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module ps2_component
# | 
set_module_property NAME ps2_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Peripherals
set_module_property DISPLAY_NAME ps2_component
set_module_property TOP_LEVEL_HDL_FILE ps2_component.v
set_module_property TOP_LEVEL_HDL_MODULE ps2_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file Altera_UP_PS2.v {SYNTHESIS SIMULATION}
add_file Altera_UP_PS2_Command_Out.v {SYNTHESIS SIMULATION}
add_file Altera_UP_PS2_Data_In.v {SYNTHESIS SIMULATION}
add_file ps2_component.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave associatedClock clock_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave address address Input 1
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave byteenable byteenable Input 4
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
add_interface_port avalon_slave readdata readdata Output 32
add_interface_port avalon_slave waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end PS2_CLK export Bidir 1
add_interface_port conduit_end PS2_DAT export Bidir 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave

set_interface_property interrupt_sender ASSOCIATED_CLOCK clock_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1
# | 
# +-----------------------------------
